language: node_js
matrix:
  fast_finish: true
  include:
  - os: osx
    node_js: 10
cache:
  yarn: true
  directories:
  - node_modules
before_script:
- yarn lint
script:
- yarn dist
- yarn test
notifications:
  email: false
